"""Structured straight-line C++ source emission."""
from __future__ import annotations

from trading_dsl_engine.cpp_new.cpp_ast import Block, Declaration, Function, Include, Namespace, Raw, Statement, Struct, TranslationUnit
from trading_dsl_engine.cpp_new.ir import FormulaIR, KernelNode


def _parameter(node: KernelNode, name: str, default: str = "0") -> str:
    return dict(node.parameters).get(name, default)


def _emit_kernel(node: KernelNode, *, direct_root: bool) -> tuple:
    children = ", ".join(f"v{child}" for child in node.children)
    name = f"v{node.id}"
    if node.opcode == "input":
        return (Declaration("auto", name, f"input.column({_parameter(node, 'input_index')})"),)
    if node.opcode == "literal":
        return (Declaration("double", name, _parameter(node, "literal"), "const"),)
    if node.opcode == "ewm":
        destination = "output.span()" if direct_root else f"state.scratch.at<double>({_parameter(node, 'scratch_offset')}, input.width)"
        return (
            Declaration("auto", name, destination),
            Statement(f"ewm_tick(state.ewm_{node.id}, {children}, {name}, {_parameter(node, 'param')}, {_parameter(node, 'adjust', 'false')}, {_parameter(node, 'ignore_na', 'true')})"),
        )
    if node.opcode == "xs_rank":
        destination = "output.span()" if direct_root else f"state.scratch.at<double>({_parameter(node, 'scratch_offset')}, input.width)"
        return (
            Declaration("auto", name, destination),
            Statement(f"xs_rank_tick({children}, state.rank_{node.id}, {name}, normal_score)"),
        )
    if node.opcode == "ridge":
        return (Declaration("auto", name, f"ridge_tick(state.ridge_{node.id}, {children}, state.ridge_scratch_{node.id})"),)
    if node.opcode == "get_beta":
        return (Declaration("auto", name, f"v{node.children[0]}.beta", "const"),)
    if node.opcode in {"add", "sub", "mul", "div"}:
        return (Declaration("auto", name, f"elementwise_{node.opcode}({children})"),)
    raise NotImplementedError(node.opcode)


def build_translation_unit(ir: FormulaIR) -> TranslationUnit:
    tick_body = [Statement("(void)workers", "schedule selected during lowering")]
    for node in ir.nodes:
        tick_body.extend(_emit_kernel(node, direct_root=node.id == ir.outputs[0].node and ir.outputs[0].direct_write))
    if not ir.outputs[0].direct_write:
        tick_body.append(Statement(f"output.assign(v{ir.outputs[0].node})"))
    tick = Function(
        "void", "tick",
        ("FormulaState& state", "const InputRow& input", "OutputRow output", "WorkerContext& workers"),
        Block(tuple(tick_body)), "inline",
    )
    batch = Function(
        "void", "batch",
        ("FormulaState& state", "const BatchInput& input", "BatchOutput& output", "WorkerContext& workers"),
        Block((Raw("for (std::size_t row = 0; row < input.rows; ++row)"), Raw("  tick(state, input.row(row), output.row(row), workers);"))),
        "inline",
    )
    state_members = [Declaration("AlignedArena", "persistent"), Declaration("AlignedArena", "scratch")]
    state_members.extend(Declaration(slot.family, f"{slot.family.removesuffix('State').lower()}_{slot.node}") for slot in ir.states)
    state_members.extend(
        Declaration("XsRankScratch", f"rank_{node.id}") if node.opcode == "xs_rank" else Declaration("RidgeScratch", f"ridge_scratch_{node.id}")
        for node in ir.nodes if node.opcode in {"xs_rank", "ridge"}
    )
    namespace = Namespace("tde::cpp_new::generated", (
        Raw(f'static constexpr char kIrDigest[] = "{ir.digest}";'),
        Struct("FormulaState", tuple(state_members)), tick, batch,
    ))
    return TranslationUnit(
        (Include("native/abi.hpp"), Include("native/operators/ewm.hpp"), Include("native/operators/xs_rank.hpp"), Include("native/operators/ridge.hpp")),
        (namespace,), "generated by trading_dsl_engine.cpp_new; do not edit",
    )


def emit_source(ir: FormulaIR) -> str:
    return build_translation_unit(ir).render()
