"""Strongly typed genetic programming over row and tensor trading expressions."""

from flows.gp.factory import (
    ALL_CPP_STREAM_UTIL_NAMES,
    ALL_DSL_OPERATOR_NAMES,
    BASE_EXPECTED_GP_OPERATOR_NAMES,
    EXCLUDED_DSL_OPERATOR_NAMES,
    EXPECTED_DSL_OPERATOR_NAMES,
    EXPECTED_GP_OPERATOR_NAMES,
    EXTRA_DSL_OPERATOR_NAMES,
    GP_COMPOSITE_OPERATOR_NAMES,
    GPConfig,
    ROWWISE_RIDGE_COMPOSITE_NAMES,
    TENSOR_CPP_STREAM_UTIL_NAMES,
    gp_input_types,
    make_pset,
    primitive_names_for_operator,
)
from flows.gp.generation import individual_to_expr, make_toolbox, random_formula, random_tree
from flows.gp.grammar import (
    GRAMMAR_SECTIONS,
    GrammarPolicy,
    format_grammar_table,
    grammar_families,
    grammar_rows,
)
from flows.gp.regression import REGRESSION_PROJECTIONS
from flows.gp.signatures import format_signature_table, signature_rows
from flows.gp.tensor_types import (
    BookPriceMatrix,
    BookVolumeMatrix,
    BoolMatrix,
    CountMatrix,
    DEFAULT_TENSOR_FIELDS,
    DerivedNumericMatrix,
    DimensionlessMatrix,
    NumericMatrix,
    NumericTensor,
    TensorFieldSpec,
    TensorIndex,
    reduced_type,
    tensor_input_types,
    tensor_rank,
    tensor_semantic,
    tensor_type,
    tensor_types_for_rank,
)
from flows.gp.testing import (
    CheckResult,
    DynamicShock,
    GenoContext,
    GenoReport,
    GenoTest,
    NoiseSpec,
    PhenoContext,
    PhenoReport,
    PhenoTest,
    PhenoTrial,
    StaticShock,
    geno_context,
    geno_forbid_families,
    geno_max_depth,
    geno_max_nodes,
    geno_require_families,
    pheno_finite,
    pheno_stability,
    run_geno_tests,
    run_pheno_tests,
    shock_dynamic_leaves,
    shock_static_terminals,
)
from flows.gp.types import (
    AxisSpec,
    BoolParam,
    BoolRow,
    CountRow,
    DatetimeUnit,
    DerivedNumericRow,
    DimensionlessRow,
    DurationRow,
    ExprValue,
    FilterHSpec,
    FilterTSpec,
    FrequencySpec,
    GroupKeyInput,
    GroupVectorInput,
    KthIgnoreSpec,
    NumericRow,
    PeriodAtLeastTwo,
    PositiveFloat,
    PositiveInt,
    PositiveNumber,
    PriceRow,
    QuantileParam,
    QuantityRow,
    RegressionReturnSpec,
    ScalarNumber,
    StaticValue,
    TimestampRow,
    TradingDayHorizonRow,
    VALUE_TYPES,
)
from flows.gp.visualization import (
    GPGraphEdge,
    GPGraphModel,
    GPGraphNode,
    GPTypeRelation,
    build_gp_graph,
    explore_gp,
    filter_gp_graph,
    gp_explorer_html,
)

__all__ = [name for name in globals() if not name.startswith("_")]
