from trading_dsl_engine.cpp_stream.python.codegen import render_translation_unit
from trading_dsl_engine.cpp_stream.python.lowering import lower_program
from trading_dsl_engine.ir import compile_ir


def _render(formula: str, *, n: int = 5) -> str:
    program = compile_ir(formula)
    plan = lower_program(program, n_instruments=n)
    return render_translation_unit(plan, n_instruments=n, prefetch_rows=16).text


def test_cpp_stream_codegen_uses_packaged_jinja_template():
    source = _render("xs_rank(ewm(close / open, 21))")
    assert source.startswith("// Generated by trading_dsl_engine.cpp_stream/python/templates/runner.cpp.j2.")
    assert "stackdsl::EwmNode<" in source
    assert "stackdsl::XsRankNode<" in source
    assert "{%" not in source
    assert "{{" not in source


def test_grouped_codegen_selects_optimized_group_policies():
    source = _render(
        "groupby((univ([0, 1], [2, 3, 4]), key), close, xs_rank(ewm(cumsum(self_), 21)))"
    )
    assert "stackdsl::FastGroupedEwmNode<" in source
    assert "stackdsl::FastGroupedXsRankNode<" in source
    assert "CppStreamInner" in source
