from pathlib import Path
import re

from trading_dsl_engine.base.dsl import cumsum, ewm, groupby, self_, univ, var
from trading_dsl_engine.base.keys import Key
from trading_dsl_engine.cpp_stream.python.frontend import compile_ir
from trading_dsl_engine.cpp_stream.python.codegen import render_translation_unit
from trading_dsl_engine.cpp_stream.python.lowering import lower_program
from trading_dsl_engine.cpp_stream.python.npy import InputTypeSpec


_ROW_LOOP_HEADERS = (
    "for (std::size_t t = 0; t < rows; ++t) {",
    "for (std::size_t t = row_begin; t < row_end; ++t) {",
)


def _render(formula, *, n: int = 5) -> str:
    program = compile_ir(formula)
    plan = lower_program(program, n_instruments=n)
    return render_translation_unit(plan, n_instruments=n, prefetch_rows=16).text


def _generated_row_loop_header(source: str) -> str:
    matches = [header for header in _ROW_LOOP_HEADERS if header in source]
    assert len(matches) == 1, matches
    return matches[0]


def test_cpp_stream_codegen_uses_packaged_jinja_template():
    source = _render("xs_rank(ewm(close / open, 21))")
    assert source.startswith(
        "// Generated by trading_dsl_engine.cpp_stream/python/templates/runner.cpp.j2."
    )
    assert "stackdsl::EwmNode<" in source
    assert "stackdsl::XsRankNode<" in source
    assert "stackdsl::DirectExecution<5>" in source
    assert "{%" not in source
    assert "{{" not in source


def test_grouped_codegen_changes_only_execution_scope():
    source = _render(
        "groupby((univ([0, 1], [2, 3, 4]), key), close, "
        "xs_rank(ewm(cumsum(self_), 21)))"
    )
    assert "stackdsl::CumsumNode<" in source
    assert "stackdsl::EwmNode<" in source
    assert "stackdsl::XsRankNode<" in source
    assert "stackdsl::GroupedExecution<N, Capacity, PartitionCount>" in source
    assert "GroupedCumsumNode" not in source
    assert "GroupedEwmNode" not in source
    assert "GroupedXsRankNode" not in source
    assert "FastGrouped" not in source
    assert "CppStreamInner" in source


def test_groupby_header_contains_no_operator_implementations():
    import trading_dsl_engine.cpp_stream as cpp_stream

    root = Path(cpp_stream.__file__).resolve().parent
    text = (root / "cpp" / "stackdsl" / "ops" / "groupby.hpp").read_text()
    assert "CumsumNode" not in text
    assert "EwmNode" not in text
    assert "XsRankNode" not in text
    assert "RidgeNode" not in text


def test_key_descriptor_selects_dense_row_scalar_resolver():
    formula = groupby(
        (
            univ([0], [1, 2], list(range(3, 9))),
            Key(var("minute"), num_keys=60, row_scalar=True, dtype="int64"),
        ),
        var("close"),
        ewm(cumsum(self_), 3),
    )
    program = compile_ir(formula)
    assert program.input_names == ("_ev_ts", "close")
    group_op = program.nodes[program.output_id].op
    assert group_op.key_specs[0].num_keys == 60
    assert group_op.key_specs[0].row_scalar is True
    assert group_op.key_specs[0].dtype == "int64"

    input_types = (
        InputTypeSpec("int64", 1),
        InputTypeSpec("float64", 9),
    )
    plan = lower_program(
        program,
        n_instruments=9,
        input_dtypes=tuple(spec.dtype for spec in input_types),
    )
    source = render_translation_unit(
        plan,
        n_instruments=9,
        prefetch_rows=16,
        input_types=input_types,
    ).text
    assert "stackdsl::FloorOp" in source
    assert "stackdsl::ModOp" in source
    assert "stackdsl::DenseTupleGroupResolver<" in source
    assert "stackdsl::KeySpec<" in source
    assert ", 60, 0, true>" in source
    assert "stackdsl::GroupedExecution<N, Capacity, PartitionCount>" in source
    assert "std::int64_t" in source
    assert "stackdsl::DivOp" in source
    assert "stackdsl::ModOp" in source


def test_tuple_of_key_descriptors_uses_mixed_radix_dense_capacity():
    formula = groupby(
        (
            univ([0, 1], [2, 3, 4]),
            Key(var("venue"), num_keys=3, offset=10, dtype="int32"),
            Key(var("bucket"), num_keys=4, row_scalar=True, dtype="uint32"),
        ),
        var("close"),
        cumsum(self_),
    )
    program = compile_ir(formula)
    assert program.input_names == ("venue", "bucket", "close")
    input_types = (
        InputTypeSpec("int32", 5),
        InputTypeSpec("uint32", 1),
        InputTypeSpec("float64", 5),
    )
    plan = lower_program(
        program,
        n_instruments=5,
        input_dtypes=tuple(spec.dtype for spec in input_types),
    )
    group = next(stage.group for stage in plan.stages if stage.group is not None)
    assert group.dense is True
    assert group.capacity == (3 + 1) * (4 + 1)
    source = render_translation_unit(
        plan,
        n_instruments=5,
        prefetch_rows=16,
        input_types=input_types,
    ).text
    assert "stackdsl::DenseTupleGroupResolver<" in source
    assert source.count("stackdsl::KeySpec<") >= 2
    assert "stackdsl::InputSrc<0, std::int32_t, 5>" in source
    assert "stackdsl::InputSrc<1, std::uint32_t, 1>" in source
    assert ", 3, 10, false>" in source
    assert ", 4, 0, true>" in source


def test_codegen_embeds_typed_row_widths_and_promotes_only_at_operation():
    program = compile_ir("close + _ev_ts")
    input_types = (
        InputTypeSpec("float64", 9),
        InputTypeSpec("int64", 1),
    )
    plan = lower_program(
        program,
        n_instruments=9,
        input_dtypes=tuple(spec.dtype for spec in input_types),
    )
    source = render_translation_unit(
        plan,
        n_instruments=9,
        prefetch_rows=16,
        input_types=input_types,
    ).text
    assert "stackdsl::InputSrc<0, double, 9>" in source
    assert "stackdsl::InputSrc<1, std::int64_t, 1>" in source
    assert "stackdsl::BinaryNode<9," in source
    assert "stackdsl::OutputDst, double, stackdsl::AddOp" in source
    assert "cpp_stream_run_arrays" in source


def test_generated_runtime_has_one_row_pass_and_cse_for_repeated_cat_branches():
    source = _render("cat(close + 1, close + 1, close + 2)")
    header = _generated_row_loop_header(source)
    assert sum(source.count(candidate) for candidate in _ROW_LOOP_HEADERS) == 1
    assert source.count(header) == 1
    assert source.count("ctx.inputs[0] =") == 1
    assert source.count("stackdsl::BinaryNode<5,") == 2
    assert source.count("stackdsl::CatNode<") == 1


def test_ridge_consumes_cat_as_lazy_feature_list_without_cat_materialization():
    source = _render(
        "get_preds(Ridge(cat(x1, x2, x3), y=y, hl=64, lambda_=0.1))",
        n=9,
    )
    assert "stackdsl::RidgeNode<" in source
    assert "stackdsl::FeatureList<" in source
    assert "stackdsl::CatNode<" not in source


def test_statistics_codegen_selects_specialized_allocation_free_nodes():
    source = _render(
        "cat(xs_pct_rank(x), ewm_cov(x, y, halflife=3), "
        "rolling_max(x, periods=5), "
        "rolling_theilsen(y, x, periods=5))",
        n=9,
    )
    assert "stackdsl::XsPctRankNode<" in source
    assert "stackdsl::EwmStatsNode<" in source
    assert "stackdsl::EwmCovarianceProjection" in source
    assert "stackdsl::RollingExtremaNode<" in source
    assert "stackdsl::RollingTheilSenNode<" in source


def test_statistics_and_ridge_projections_keep_generic_execution_nodes():
    grouped = _render(
        "groupby(key, x, rolling_max(self_, periods=5))",
        n=9,
    )
    assert "stackdsl::RollingExtremaNode<" in grouped
    assert "stackdsl::GroupedExecution<N, Capacity, PartitionCount>" in grouped
    assert "GroupedRolling" not in grouped

    ridge = _render(
        "get_standard_error("
        "Ridge(cat(x1, x2), y=y, weights=w, hl=8, lambda_=0.2), 1)",
        n=9,
    )
    assert "stackdsl::RidgeNode<" in ridge
    assert "stackdsl::RidgeStandardErrorProjection<1>" in ridge
    assert "GroupedRidge" not in ridge


def test_complex_stateless_stages_are_adjacent_inside_one_row_loop():
    source = _render("xs_rank((x + 5 + y) * 3)", n=9)
    header = _generated_row_loop_header(source)
    loop_start = source.index(header)
    last_call_text = "s3.on_data(ctx);"
    last_call = source.index(last_call_text, loop_start)
    row_loop_prefix = source[loop_start : last_call + len(last_call_text)]

    stage_calls = re.findall(
        r"^\s+s(\d+)\.on_data\(ctx\);$",
        row_loop_prefix,
        re.MULTILINE,
    )
    assert stage_calls == ["0", "1", "2", "3"]
    assert source.count("stackdsl::BinaryNode<9,") == 3
    assert source.count("stackdsl::XsRankNode<9,") == 1
    assert sum(source.count(candidate) for candidate in _ROW_LOOP_HEADERS) == 1
    assert row_loop_prefix.count("ctx.inputs[0] =") == 1
    assert row_loop_prefix.count("ctx.inputs[1] =") == 1


def test_temporal_reduction_suffix_runs_once_during_finalization():
    source = _render(var("x").sum(axis=0) + 1.0, n=5)
    loop_start = source.index(_generated_row_loop_header(source))
    loop_end = source.index("        return 0;\n    }", loop_start)
    row_loop = source[loop_start:loop_end]

    # s0 accumulates the temporal reduction. Its result consumers are omitted
    # from the row loop rather than projecting the cumulative result every row.
    assert re.findall(
        r"^\s+s(\d+)\.on_data\(ctx\);$", row_loop, re.MULTILINE
    ) == ["0"]

    final_start = source.index("    int finalize(")
    final_end = source.index("        return 0;\n    }", final_start)
    final_phase = source[final_start:final_end]
    calls = (
        "s0.finalize(ctx);",
        "s1.on_data(ctx);",
        "s2.on_data(ctx);",
        "s2.finalize(ctx);",
    )
    positions = [final_phase.index(call) for call in calls]
    assert positions == sorted(positions)
